# Generated by Django 3.1.7 on 2021-03-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vid',
            field=models.CharField(default='g4mQmLZ-lEw', max_length=20),
        ),
    ]
